# Generated by Django 2.0.4 on 2019-02-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='accesibilidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='lomejor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lugar',
            name='promociones',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lugar',
            name='reglas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='servicios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
