# Generated by Django 2.0.4 on 2018-04-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='photos',
            field=models.ManyToManyField(to='api.Photo'),
        ),
    ]
