# Generated by Django 2.0.4 on 2018-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lugar_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
