# Generated by Django 2.0.4 on 2018-04-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='photos',
        ),
    ]
