# Generated by Django 2.0.4 on 2018-04-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_lugar_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lugar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.Lugar'),
        ),
    ]
