# Generated by Django 2.0.4 on 2019-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_invitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='sugerido',
            field=models.BooleanField(default=False),
        ),
    ]
