# Generated by Django 2.0.4 on 2019-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lugar_sugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='nuevo',
            field=models.BooleanField(default=True),
        ),
    ]
