# Generated by Django 2.0.4 on 2019-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lugar_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='login_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='config',
            name='conekta_private',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='conekta_public',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
