# Generated by Django 2.0.4 on 2018-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_photo_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set(),
        ),
    ]
