# Generated by Django 2.0.4 on 2018-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180421_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='zone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
