# Generated by Django 2.0.4 on 2019-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_config_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cupon',
            field=models.FloatField(default=0),
        ),
    ]
