# Generated by Django 2.0.4 on 2018-04-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180422_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tipo',
            field=models.CharField(choices=[('lugar', 'Lugar'), ('producto', 'Producto')], default='lugar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Category'),
        ),
    ]
