# Generated by Django 2.0.4 on 2019-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
