# Generated by Django 2.0.4 on 2019-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_config_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_entrega',
            field=models.CharField(choices=[('draft', 'Pendiente'), ('done', 'Entregada'), ('cancel', 'Cancelada')], default='draft', max_length=255),
        ),
    ]
