<<<<<<< HEAD
# Generated by Django 2.0.4 on 2019-07-18 16:27
=======
# Generated by Django 2.0.4 on 2019-07-18 17:28
>>>>>>> 985408985fd6fcbab3943b90c5e324255dbf48de

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_status_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('cancel', 'Bloqueada')], default='active', max_length=255),
        ),
    ]
