# Generated by Django 2.0.4 on 2019-07-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190723_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('state', models.CharField(choices=[('draft', 'Pendiente'), ('done', 'Realizado')], default='draft', max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_porcentaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lugar')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cobro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cobro'),
        ),
    ]
