# Generated by Django 2.0.4 on 2019-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190730_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='fecha',
            field=models.DateField(),
        ),
    ]
