# Generated by Django 2.0.4 on 2018-04-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180426_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Lugar'),
        ),
    ]
