# Generated by Django 2.0.4 on 2019-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190801_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='payment_info',
            field=models.TextField(default=''),
        ),
    ]
