# Generated by Django 2.0.4 on 2018-04-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180428_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
