# Generated by Django 2.0.4 on 2018-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_lugar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
