# Generated by Django 2.0.4 on 2019-08-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190801_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.FloatField(verbose_name=2),
        ),
    ]
