# Generated by Django 2.0.4 on 2018-06-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180617_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
