# Generated by Django 2.0.4 on 2018-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180708_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='puntuacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
