# Generated by Django 2.0.4 on 2018-07-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Pendiente'), ('done', 'Realizado')], default='draft', max_length=255),
        ),
    ]
