# Generated by Django 2.0.4 on 2018-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
