# Generated by Django 2.0.4 on 2018-07-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_order_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Lugar'),
        ),
    ]
