# Generated by Django 2.0.4 on 2018-07-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_order_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lugar'),
        ),
    ]
