# Generated by Django 2.0.4 on 2018-08-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_lugar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
