# Generated by Django 2.0.4 on 2018-08-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_lugar_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
