# Generated by Django 2.0.4 on 2018-08-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180802_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='clear_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
