# Generated by Django 2.0.4 on 2018-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_lugar_clear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='mapa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
